name: "Docker Scout report"
on:
  workflow_dispatch
jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      baseimages: ${{ steps.baseimages.outputs.baseimages }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Find Dockerfiles
        id: baseimages
        run: |
          chmod +x ./github/scripts/base_images.sh
          baseimages=$(./github/scripts/base_images.sh)
          echo "baseimages=${baseimages}"
          echo "baseimages=${baseimages}" >> $GITHUB_OUTPUT
  report:
    runs-on: ubuntu-latest
    needs: prepare
    if: ${{ needs.prepare.outputs.baseimages != '' }}
    strategy:
      matrix:
        image: ${{ fromJson(needs.prepare.outputs.baseimages).baseimages }}
    steps:
      - name: Analyze for critical and high CVEs
        id: docker-scout-cves
        if: ${{ github.event_name != 'pull_request_target' }}
        uses: docker/scout-action@v1
        with:
          command: cves,recommendaions
          image: ${{ matrix.image }}
          sarif-file: sarif.output.json
          summary: true

      - name: Upload SARIF result
        id: upload-sarif
        if: ${{ github.event_name != 'pull_request_target' }}
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: sarif.output.json
